version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    networks:
      - app-network

  app:
    build: .
    command: ["./bin/rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    restart: always
    volumes:
      - .:/home/rails
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
      - es
    environment:
      DB_USER: user
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
      REDIS_URL: redis://redis:6379
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - node.name=es
      - cluster.name=cluster
      - discovery.seed_hosts=es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200
    networks:
      - app-network

  sidekiq:
    depends_on:
      - 'redis'
      - 'db'
    build: .
    restart: always
    command: bundle exec sidekiq
    volumes:
      - .:/home/rails
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_USER=user
      - DB_NAME=app
      - DB_PASSWORD=password
      - DB_HOST=db
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  es:
  db:
